---
title: |
 | <font size="5" color="black"> SBWL Handel & Marketing </font> <br/> Introduction to R <br/> <font size="5">Institute for Retailing & Data Science</font> 

layout: true
output:
  xaringan::moon_reader:
    self_contained: true
    includes:
      after_body: insert-logo.html
    css: [default, mysty.css]
    lib_dir: libs
    nature:
      ratio: '16:9'
      titleSlideClass: [left]
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: "%current%"
---


```{r xaringan-panelset, echo=FALSE}
xaringanExtra::use_panelset()
```

```{r xaringan-animate-css, echo=FALSE}
xaringanExtra::use_animate_css()
```

```{css echo=FALSE}
.hide-count .remark-slide-number {
  display: none;
}
  
```
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```


# A slide

___

- Point 1
--

- Point 2

```{r}
print("Hello World!")
```

---


# A plot

___

.pull-left[
```{r plot-label, eval=FALSE}
library(tidyverse)
data(penguins, package = "palmerpenguins")
ggplot(penguins) + 
  aes(bill_length_mm, 
      flipper_length_mm, 
      color = species,
      shape = sex) + 
  labs(x = "Bill length (mm)", 
       y = "Flipper length (mm)") +
  geom_point() +
  theme_bw()
```
]

--

class: animated fadeIn 


.pull-right[

```{r plot-label-out, dpi=300,ref.label="plot-label", echo=FALSE, warning=FALSE, message=FALSE, fig.height=5.5}
```
]


---

class: hide-footer

# Slide panel

___

.panelset[
.panel[
.panel-name[R code]
```{r plot-density, eval=FALSE}
ggplot(penguins) + 
  aes(bill_length_mm, 
      color = species) + 
  geom_density()
```
]
.panel[
.panel-name[Plot]
```{r plot-density-out, dpi=300,ref.label="plot-density", echo=FALSE, warning=FALSE, message=FALSE, fig.height=2.7}
```
]
.panel[.panel-name[with Theme]
.pull-left[
```{r plot-theme, eval=FALSE}
ggplot(penguins) + 
  aes(bill_length_mm, 
      color = species) + 
  geom_density() +
  theme_bw()
```
]
.pull-right[
```{r plot-theme-out, dpi=300,ref.label="plot-theme", echo=FALSE, warning=FALSE, message=FALSE, fig.height=5}
```
]]
]

---

class: hide-footer hide-logo-bottom

## Hide footer, bottom logos,<br/> and divider


```{r, fig.align='center', dpi=300, fig.width=20, fig.height=8}
plot(rnorm(100))
```

---

class: logo-small hide-footer hide-logo-bottom

## Hide bottom, hide footer, shrink top WU

___

```{r, fig.align='center', dpi=300, fig.width=20, fig.height=8.5}
plot(rnorm(100))
```

